### ISSUE TITLE
Error in install: "Running the contributed command:'extension.copyGitHubLinkToClipboard' failed."

### ISSUE THREAD

**Issue by shannongatta1** [dai-shi/es-beautifier#16] opened 2018-04-13 20:56 UTC
Been trying desperately to get the Initialize repo button on my source control or on the activity bar to no avail. tried Ctrl+LC and got this error. Don't know if it would've solved my problem, but I need help.

**Comment by dai-shi** [comment] 2018-04-14 00:34
I'm not sure if I totally follow your problem, but are you having an issue with installing the es-beautifier extension in vscode?

**Comment by shannongatta1** [comment] 2018-04-14 01:11
I don't think so, I'm just trying to install a shortcut to access GitHub on
VS code. If that's the beuatifyer, then yes?

**Comment by dai-shi** [comment] 2018-04-14 01:43
Can you upload a screenshot? I wonder what's the repo button.

**Comment by shannongatta1** [comment] 2018-04-16 16:14
![missing_shortcuts](https://user-images.githubusercontent.com/19353228/38821796-6d1909e4-4156-11e8-82c5-582f498df551.png)
![what_im_looking_for_1](https://user-images.githubusercontent.com/19353228/38821806-71de5fba-4156-11e8-8707-e0d88d970f66.png)
![what_im_looking_for_2](https://user-images.githubusercontent.com/19353228/38821810-741ff054-4156-11e8-965a-94b156eee6e4.png)
I'm a novice at VS code so if I'm missing something key, please embarrass me now.

**Comment by shannongatta1** [comment] 2018-04-16 18:18
Okay I'm realizing something now. The smaller Github shortcut next to source control pops up when i close my repository. But then whats the use of having the shortcut on the left sidebar?

**Comment by dai-shi** [comment] 2018-04-16 22:35
Thanks. Looks like the issue is not much related to the es-beautifier extension.  As I'm not that experienced in vscode, you might want to ask it somewhere else, maybe stackoverflow?

**Comment by dai-shi** [comment] 2018-07-29 23:03
Closing this issue as it's no longer active.

**Closed by dai-shi** 2018-07-29 23:03 UTC
Labels: vscode
