### ISSUE TITLE
command 'extension.es-beautifier' not found

### ISSUE THREAD

**Issue by magicspon** [dai-shi/es-beautifier#10] opened 2017-02-10 15:08 UTC
Hello,

I'm making the switch from atom to vs code.

Having some teething problems beautifying my code (it's mainly jsx stuff that is throwing a wobbly)

I've installed the extension, updated my eslintrc.json and added my key bindings.

If i use my key binding i get:
`command 'extension.es-beautifier' not found`

then if i use the default key i get this:

`es-beautifier failed. See the console log in the DevTools.`

```
es-beautifier failed: Error: Command failed: node /Users/stockley/.vscode/extensions/dai-shi.vscode-es-beautifier-0.2.2/node_modules/es-beautifier/lib/cli.js
/Users/stockley/.vscode/extensions/dai-shi.vscode-es-beautifier-0.2.2/node_modules/eslint/lib/token-store.js:41
        const end = node.range[1];
                        ^

TypeError: Cannot read property 'range' of null
    at lastTokenIndex (/Users/stockley/.vscode/extensions/dai-shi.vscode-es-beautifier-0.2.2/node_modules/eslint/lib/token-store.js:41:25)
    at SourceCode.api.getTokenAfter (/Users/stockley/.vscode/extensions/dai-shi.vscode-es-beautifier-0.2.2/node_modules/eslint/lib/token-store.js:114:23)
    at EventEmitter.enterJSXElement (/Users/stockley/.vscode/extensions/dai-shi.vscode-es-beautifier-0.2.2/node_modules/es-beautifier/lib/rules/jsx-multiline-elements.js:85:37)
    at emitOne (events.js:101:20)
    at EventEmitter.emit (events.js:188:7)
    at NodeEventGenerator.enterNode (/Users/stockley/.vscode/extensions/dai-shi.vscode-es-beautifier-0.2.2/node_modules/eslint/lib/util/node-event-generator.js:39:22)
    at CodePathAnalyzer.enterNode (/Users/stockley/.vscode/extensions/dai-shi.vscode-es-beautifier-0.2.2/node_modules/eslint/lib/code-path-analysis/code-path-analyzer.js:607:23)
    at CommentEventGenerator.enterNode (/Users/stockley/.vscode/extensions/dai-shi.vscode-es-beautifier-0.2.2/node_modules/eslint/lib/util/comment-event-generator.js:98:23)
    at Controller.enter (/Users/stockley/.vscode/extensions/dai-shi.vscode-es-beautifier-0.2.2/node_modules/eslint/lib/eslint.js:928:36)
    at Controller.__execute (/Users/stockley/.vscode/extensions/dai-shi.vscode-es-beautifier-0.2.2/node_modules/estraverse/estraverse.js:397:31)

    at checkExecSyncError (child_process.js:495:13)
    at execFileSync (child_process.js:515:13)
    at module.(anonymous function) (ELECTRON_ASAR.js:178:20)
    at execCLI (/Users/stockley/.vscode/extensions/dai-shi.vscode-es-beautifier-0.2.2/index.js:7:10)
    at Object.beautify [as provideDocumentFormattingEdits] (/Users/stockley/.vscode/extensions/dai-shi.vscode-es-beautifier-0.2.2/index.js:18:24)
    at /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:13:22729
    at /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:6:9460
    at new n.Class.derive._oncancel (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:6:5563)
    at Object.f [as asWinJsPromise] (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:6:9423)
    at e.provideDocumentFormattingEdits (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:13:22683)
```

any ideas where i'm going wrong.

thanks
dave

**Comment by dai-shi** [comment] 2017-02-10 15:38
Hi,

Since v0.2.0, this extension does not expose a command but works as a formatter.
The new usage is written in https://github.com/dai-shi/es-beautifier/blob/master/README.md#usage-visual-studio-code
The reason is explained in #6.

Please also note that es-beautifier owns its rule and does not care the user eslintrc files.
I've made a fix for this, but the feature is not confirmed. Please refer #9.
Your help would be appreciated.

Best,
Daishi

**Comment by magicspon** [comment] 2017-02-10 15:58
Hello,

thanks for your swift reply.

I'm very new to vs... where is do i find "Change Language Mode"?! :)

ta

**Comment by dai-shi** [comment] 2017-02-10 16:13
You can either enter ">Change Language Mode" in the command palette or use the shortcut key, which is Cmd-K M (if OSX) or Ctrl-K M.

Hope it helps.

**Comment by magicspon** [comment] 2017-02-10 16:16
Making progress... ;) back to 

`es-beautifier failed. See the console log in the DevTools.` 

thanks again

**Comment by dai-shi** [comment] 2017-02-10 16:26
OK, can you provide me short code that you want to beautify, which will reproduce the error? I may need to dig into it.
I can assume something like a JSX element without closing, but I want to confirm it.

**Comment by magicspon** [comment] 2017-02-10 16:36
Sure, i've created a gist with a few examples.

https://gist.github.com/magicspon/10cb94c6138fd6ffd6af5c727701cfab

Thanks

**Comment by dai-shi** [comment] 2017-02-11 01:01
With your last example, if I remove `onMarkerClick={this.onMarkerClick} {...entry}`, the error is gone. Interesting...

**Comment by dai-shi** [comment] 2017-02-11 01:07
```
x = (<Marker lat={lat} lng={lng} onMarkerClick={onMarkerClick} {...entry}/>)
```
This is the minimal example to reproduce the error.

**Closed** 2017-02-11 01:23 UTC
Labels: bug, vscode

**Comment by dai-shi** [comment] 2017-02-11 01:31
v0.2.3 is published. This fixes the error. Please try it, and if you still have problems, feel free to reopen it.

Although in your example code the chained function calls are not well indented, it's another issue that we need to fix.

**Comment by dai-shi** [comment] 2017-02-11 01:42
Well, the fundamental problem is that eslint somehow fails to parse the code. What I've done is just a workaround. Hope to fix it in the future.

**Comment by magicspon** [comment] 2017-02-11 17:04
Thanks... works like a charm
