### ISSUE TITLE
VSCode: Running the contributed command:'extension.es-beautifier' failed.

### ISSUE THREAD

**Issue by koraybalci** [dai-shi/es-beautifier#4] opened 2016-12-07 04:40 UTC
I installed the extension in VSCode 1.7.2 (latest as of now) running on node 6.5.0 and ran it on a react solution I am working on and got the following error:
"Running the contributed command:'extension.es-beautifier' failed."

PS: Is there a log file somewhere that I may help figure out what went wrong?

**Comment by con-ssc** [comment] 2016-12-07 11:42
I encountered the same problem when trying to use the command in a ts file. js files seem to work.
You can only see it in the DevTools of vscode.

**Comment by dai-shi** [comment] 2016-12-07 12:00
@koraybalci @con-ssc Thanks for reporting this issue!
Although I can't reproduce the issue in my VSCode 1.7.2 (OSX), it seems like the problem is `-` in `extension.es-beautifier`. Assuming that, I'll update the plugin.

**Comment by dai-shi** [comment] 2016-12-07 12:13
The plugin version 0.1.0 is published.
https://marketplace.visualstudio.com/items?itemName=dai-shi.vscode-es-beautifier

Please note that you need to change the keybinding configuration, like:
```
{ "key": "shift+cmd+e", "command": "extension.esBeautifier", "when": "editorTextFocus" }
```

Hope it works.

**Comment by con-ssc** [comment] 2016-12-07 12:15
Problem persists

**Comment by con-ssc** [comment] 2016-12-07 12:17
![image](https://cloud.githubusercontent.com/assets/8189808/20967367/6f7235ba-bc7f-11e6-93e4-526af9e20b69.png)

**Comment by dai-shi** [comment] 2016-12-07 12:18
@con-ssc Does it happen when you type "es-beautifier" in the command palette? maybe so.

**Comment by con-ssc** [comment] 2016-12-07 12:20
Yes, I have looked through all commands in the keybindings and yours is not available to select

**Comment by dai-shi** [comment] 2016-12-07 12:26
@con-ssc Oh, so you mean it raises this error with a certain file. Does it mean if say an empty file, it won't raise this error?

**Comment by dai-shi** [comment] 2016-12-07 12:30
BTW, the keybindings are not added by the plugin by default. You need to write a configuration by your own, at this point.

**Comment by con-ssc** [comment] 2016-12-07 12:57
I know, and I checked all command suggestions and yours was not there.

**Comment by dai-shi** [comment] 2016-12-07 14:12
I think I misunderstood the original issue. Let me try to log the error.

**Comment by dai-shi** [comment] 2016-12-07 16:09
Published v0.1.1.
It should now show errors in the DevTools.
@koraybalci @con-ssc

**Comment by koraybalci** [comment] 2016-12-08 00:09
now I get: "es-beautifier failed. See the cons ole log in the DevTools." with these on dev console;

> `extensionHost.ts:255 [Extension Host] es-beautifier failed: Error: spawnSync C:\Users\balciko\.vscode\extensions\dai-shi.vscode-es-beautifier-0.1.1\node_modules\es-beautifier\lib\cli.js UNKNOWN
    at exports._errnoException (util.js:1026:11)
    at spawnSync (child_process.js:473:20)
    at execFileSync (child_process.js:510:13)
    at module.(anonymous function) (ELECTRON_ASAR.js:168:20)
    at execCLI (C:\Users\balciko\.vscode\extensions\dai-shi.vscode-es-beautifier-0.1.1\index.js:6:10)
    at beautify (C:\Users\balciko\.vscode\extensions\dai-shi.vscode-es-beautifier-0.1.1\index.js:17:26)
    at t.$executeContributedCommand (c:\Program Files (x86)\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:10:25694)
    at t.e.handle (c:\Program Files (x86)\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:10:10602)
    at s (c:\Program Files (x86)\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:7:21356)
    at p (c:\Program Files (x86)\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:7:22033)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)I.logExtensionHostMessage @ extensionHost.ts:255I.onMessaage @ extensionHost.ts:196(anonymous function) @ extensionHost.ts:141emitTwo @ events.js:106emit @ events.js:191process.nextTick @ internal/child_process.js:744_combinedTickCallback @ internal/process/next_tick.js:67_tickCallback @ internal/process/next_tick.js:98`

**Comment by dai-shi** [comment] 2016-12-08 00:24
@koraybalci Thanks! Now, the issue is clear, and I need to learn a little bit of Windows. Please be patient.

(which means, the issue reported by @con-ssc is something different.)

**Comment by dai-shi** [comment] 2016-12-08 03:29
v0.1.2 is published.
Could you give it a try? @koraybalci

**Comment by con-ssc** [comment] 2016-12-08 07:47
It can execute now, but the result is not so satisfying. For example, it leaves inconsistent indent spacing, a mix of spaces and tabs. And also a mix of 2 spaces and 4 spaces indentation.

**Comment by dai-shi** [comment] 2016-12-08 08:20
@con-ssc So, is your problem the same as this issue (Windows)?

> For example, it leaves inconsistent indent spacing, a mix of spaces and tabs. And also a mix of 2 spaces and 4 spaces indentation.

That's not what I would expect. Isn't it just unchanged? You said you are using typescript?

**Comment by con-ssc** [comment] 2016-12-08 08:48
This time it was an js file

**Comment by dai-shi** [comment] 2016-12-08 08:50
Can you share a small example?

**Comment by dai-shi** [comment] 2016-12-08 08:50
(Maybe we should file a new issue, if it's not vscode specific.)

**Comment by con-ssc** [comment] 2016-12-08 14:51
Quick example is J-I-C.js from https://github.com/brunobar79/J-I-C
![image](https://cloud.githubusercontent.com/assets/8189808/21014373/0bc08000-bd5e-11e6-9f6a-1936fecdf80f.png)
![image](https://cloud.githubusercontent.com/assets/8189808/21014388/1a293b82-bd5e-11e6-9870-bf7800196a8b.png)

**Comment by dai-shi** [comment] 2016-12-08 23:16
@con-ssc Thanks for the example. Let me open a new issue for this.

@koraybalci Please let me know if your issue is also resolved.

**Comment by dai-shi** [comment] 2016-12-10 04:21
Closing this issue. Please feel free to reopen it if the problem remains.

**Closed by dai-shi** 2016-12-10 04:21 UTC
Labels: bug, vscode

**Comment by koraybalci** [comment] 2016-12-11 22:56
I confirm, it's not crashing anymore.
